# example dataset
example:
  images: './example/data/images'
  images_skulling: './example/data/images_skulling'
  annotations: './example/data/annotations'
  masks: './example/data/masks'
  transforms: './example/output/output_registration/transforms'
  registered: './example/output/output_registration/registered'

  draw_axial_annotation: './example/output/output_annotations/axial/sub-stroke0001_axial_021.csv'
  draw_axial_image: './example/output/output_slices/axial/sub-stroke0001_axial_021.tif'

  draw_coronal_annotation: './example/output/output_annotations/coronal/sub-stroke0001_bbox_coronal_316.csv'
  draw_coronal_image: './example/output/output_annotations/coronal/sub-stroke0001_bbox_coronal_316.csv'

  draw_sagittal_annotation: './example/output/output_annotations/sagittal/sub-stroke0001_bbox_sagittal_327.csv'
  draw_sagittal_image: './example/output/output_slices/sagittal/sub-stroke0001_sagittal_327.tif'

# dataset template
my_dataset:
  images: ''
  annotations: ''
  masks: ''
  transforms: ''
  registered: ''

# template
template:
  MNI152:
    image: './template/MNI152_T1_0.5mm_%32.nii.gz'
    brain: './template/MNI152_T1_0.5mm_brain_%32.nii.gz'
    mask: './template/MNI152_T1_0.5mm_brain_mask_%32.nii.gz'